#!/usr/bin/env python

import os
import re
import sys

arguments = sys.argv[1:]
urls = []

print('Downloading from the urls:')
for package in arguments:

    m = re.search(r'([a-zA-Z0-9\-]+)-(\d+.+)',package)

    name = m.group(1)
    version = m.group(2)

    url = 'https://archive.archlinux.org/packages/'

    url += f'{name[0]}/{name}/{name}-{version}-x86_64.pkg.tar.zst'

    print(url)
    urls.append(url)

print('')
os.system(f'sudo pacman -U {' '.join(urls)}')


